common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('modify/<str:username>/', views.modify, name='modify'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import facebook.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('facebook/', include('facebook.urls')),
    path('', facebook.views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

facebook/urls.py
from django.urls import path
from . import views

app_name='facebook'

urlpatterns = [
    path('', views.home, name='home'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/<str:username>/', views.post_user, name='post_user'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('comment/create/post/<int:post_id>/<str:before>/', views.comment_create_post, name='comment_create_post'),
    path('comment/modify/question/<int:comment_id>/<str:before>/', views.comment_modify_post, name='comment_modify_post'),
    path('comment/delete/question/<int:comment_id>/<str:before>/', views.comment_delete_post, name='comment_delete_post'),
    path('vote/post/<int:post_id>/<str:before>/', views.vote_post, name='vote_post'),
    path('follow/', views.follow, name='follow'),
    path('follow/<str:username>/', views.following, name='following'),
    path('unfollow/<str:username>/', views.unfollowing, name='unfollowing'),
    path('follow/all/<str:username>/', views.follow_all, name='follow_all'),
    path('follower/all/<str:username>/', views.follower_all, name='follower_all'),
]

facebook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

from common.models import Profile

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, blank=True, related_name='voter_post')

    def __str__(self):
        return self.title

    def profile(self):
        profile = get_object_or_404(Profile, user=self.author)
        return profile

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)

facebook/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post    # 사용할 모델
        fields = ['title', 'image', 'content']     # PostForm에서 사용할 Post 모델의 속성

        labels = {
            'title': '제목',
            'image': '이미지',
            'content': '내용',
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'rows': 10}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

facebook/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.models import User

from common.models import Profile
from .models import Post, Comment
from .forms import PostForm, CommentForm

def home(request):
    users = request.user
    posts = Post.objects.order_by('-create_date')
    context = {'posts' : posts, 'users':users}
    return render(request, 'facebook/home.html', context)

def post_user(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    posts = Post.objects.filter(author=user)
    context = {'users' : user, 'posts' : posts, 'profile' : profile}
    return render(request, 'facebook/post_user.html', context)

@login_required(login_url='common:login')
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.create_date = timezone.now()
            post.save()
            return redirect('facebook:post_user', username=post.author.username)
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'facebook/post_form.html', context)

@login_required(login_url='common:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('facebook:post_user', username=post.author.username)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.modify_date = timezone.now()  # 수정일시 저장
            post.save()
            return redirect('facebook:post_user', username=post.author.username)
    else:
        form = PostForm(instance=post)
    context = {'form': form}
    return render(request, 'facebook/post_form.html', context)

@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('facebook:post_user', username=post.author.username)
    post.delete()
    return redirect('facebook:post_user', username=post.author.username)

@login_required(login_url='common:login')
def comment_create_post(request, post_id, before):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.post = post
            comment.save()
            if(before=='home'):
                return redirect('home')
            return redirect('facebook:post_user', post.author.username)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'facebook/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_post(request, comment_id, before):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('home')

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            if (before == 'home'):
                return redirect('home')
            return redirect('facebook:post_user', comment.post.author.username)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'facebook/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_post(request, comment_id, before):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
    else:
        comment.delete()
    if (before == 'home'):
        return redirect('home')
    return redirect('facebook:post_user', comment.post.author.username)

@login_required(login_url='common:login')
def vote_post(request, post_id, before):
    post = get_object_or_404(Post, pk=post_id)
    post.voter.add(request.user)
    if(before=='home'):
        return redirect('home')
    return redirect('facebook:post_user', post.author.username)

@login_required(login_url='common:login')
def follow(request):
    profiles = Profile.objects.all()
    user = request.user
    context = {'profiles':profiles, 'users':user}
    return render(request, 'facebook/follow.html', context)

@login_required(login_url='common:login')
def following(request, username):
    profile = get_object_or_404(Profile, user=request.user)
    user = get_object_or_404(User, username=username)
    fprofile = get_object_or_404(Profile, user=user)

    profile.follow.add(user)
    fprofile.follower.add(request.user)
    return redirect('facebook:follow')

@login_required(login_url='common:login')
def unfollowing(request, username):
    profile = get_object_or_404(Profile, user=request.user)
    user = get_object_or_404(User, username=username)
    fprofile = get_object_or_404(Profile, user=user)

    profile.follow.remove(user)
    fprofile.follower.remove(request.user)
    return redirect('facebook:follow')

def follow_all(request, username):
    profiles = []
    users = request.user
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    following = profile.follow.all()

    for f in following:
        profiles.append(get_object_or_404(Profile, user=f))

    context = {'profiles': profiles, 'users': users}
    return render(request, 'facebook/follow.html', context)

def follower_all(request, username):
    profiles = []
    users = request.user
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    following = profile.follower.all()

    for f in following:
        profiles.append(get_object_or_404(Profile, user=f))

    context = {'profiles': profiles, 'users': users}
    return render(request, 'facebook/follow.html', context)

templates/facebook/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/facebook/home.html
{% extends "base.html" %}
{% load filter %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<main role="main">
      <div class="album bg-light">
        <div class="container-sm">
            <div class="album py-5 bg-light">
              <div class="container">
                  {% for post in posts %}
                  <div class="row">
                      <div class="container">
                          <div class="card shadow-sm">
                              <a href="{% url 'facebook:post_user' post.author %}" class="list-group-item">
                                  <div class="profile-image">
                                      {% if post.profile.image %}
                                      <img src="{{post.profile.image.url}}" width="40" height="40">
                                      {% else %}
                                      <img src="{% static 'profile.jpg' %}" width="40" height="40">
                                      {% endif %}
                                  </div>
                                  <div style="margin-left:50px; margin-top:6px;">{{ post.author }}</div>

                              </a>
                              <img class="card-img-top" src="{{ post.image.url }}" alt=" Card image cap">
                              <div class="card-body">

                                  <h4>{{ post.title }}</h4>
                                  <p class="card-text">{{ post.content }}</p>
                                  {% if post.modify_date %}
                                  <p class="card-text">{{ post.modify_date }} (수정)</p>
                                  {% else %}
                                  <p class="card-text">{{ post.create_date }}</p>
                                  {% endif %}

                                  <p class="card-text">
                                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                          <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                        </svg>
                                      {{ post.voter.count }}
                                  </p>


                                  <center>
                                      <a class="btn btn-primary btn-lg" href="{% url 'facebook:vote_post' post.id 'home' %}" class="recommend btn btn-sm btn-secondary btn-block my-1" style="width:45%;">
                                          <h5>
                                              {% confirm_like request.user.username post.id as l %}
                                              {% if l == 'like' %}
                                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                                </svg>
                                              {% else %}
                                                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                                   <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                               </svg>
                                              {% endif %}
                                              좋아요
                                          </h5>
                                      </a>
                                      <a class="btn btn-primary btn-lg" href="{% url 'facebook:comment_create_post' post.id 'home' %}" class="recommend btn btn-sm btn-secondary btn-block my-1" style="width:45%;">
                                          <h5>
                                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left" viewBox="0 0 16 16">
                                                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                                </svg>
                                              댓글 달기
                                          </h5>
                                      </a>
                                  </center>

                                  {% if post.comment_set.count > 0 %}
                                    <div class="mt-3">
                                    {% for comment in post.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                                        <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                                            <span>
                                                - {{ comment.author }},
                                                {% if comment.modify_date %}
                                                {{ comment.modify_date }} (수정)
                                                {% else %}
                                                {{ comment.create_date }}
                                                {% endif %}
                                            </span>
                                            {% if request.user == comment.author %}
                                            <a href="{% url 'facebook:comment_modify_post' comment.id 'home' %}" class="small">수정</a>,
                                            <a href="{% url 'facebook:comment_delete_post' comment.id 'home' %}" class="small delete">삭제</a>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                    </div>
                                    {% endif %}

                              </div>
                          </div>
                      </div>
                  </div>
                  <br>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>

</main>

{% endblock %}

templates/facebook/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시물 등록</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/facebook/post_user.html
{% extends 'base.html' %}
{% load filter %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div class="bodys">
    <div class="album bg-light">
        <div class="container-sm">
            <div class="album bg-light">
              <div class="container">
                  <header>
                    <div class="containers">
                        <div class="profile">
                            <div class="profile-image">
                                {% if profile.image %}
                                <img src="{{profile.image.url}}" style="padding-left:20px;" width="200" height="200">
                                {% else %}
                                <img src="{% static 'profile.jpg' %}" style="padding-left:20px;" width="200" height="200">
                                {% endif %}
                            </div>

                            <div class="profile-user-settings"><br>
                                <h1 style="padding-left:30px;">{{users.username}}</h1>

                            </div>

                            <div class="profile-stats">
                                <ul>
                                    <a href="{% url 'facebook:post_user' users.username  %}" style="text-decoration-line: none; color:black;">
                                        <li><span class="profile-stat-count">{{posts.count}}</span> posts</li>
                                    </a>
                                    <a href="{% url 'facebook:follower_all' users.username  %}" style="margin-left:20px; text-decoration-line: none; color:black;">
                                        <li><span class="profile-stat-count">{{profile.follower.count}}</span> followers</li>
                                    </a>
                                    <a href="{% url 'facebook:follow_all' users.username  %}" style="margin-left:20px; text-decoration-line: none; color:black;">
                                        <li><span class="profile-stat-count">{{profile.follow.count}}</span> following</li>
                                    </a>
                                </ul>

                                {% if request.user == users %}
                                <a href="{% url 'common:modify' users.username  %}" style="text-decoration-line: none; color:black;">
                                    <button type="submit" class="btn profile-edit-btn" href="{% url 'common:modify' users.username  %}">
                                        프로필 편집
                                    </button>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        <!-- End of profile section -->
                    </div>
                    <!-- End of container -->
                  </header>
                  {% for post in posts %}
                  <div class="row">
                      <div class="container">
                          <div class="card shadow-sm">

                              <a href="{% url 'facebook:post_user' post.author %}" class="list-group-item">
                                  <div class="profile-image">
                                      {% if profile.image %}
                                      <img src="{{profile.image.url}}" width="40" height="40">
                                      {% else %}
                                      <img src="{% static 'profile.jpg' %}" width="40" height="40">
                                      {% endif %}
                                  </div>
                                  <div style="margin-left:50px; margin-top:6px;">{{ post.author }}</div>
                              </a>
                              <img class="card-img-top" src="{{ post.image.url }}" alt=" Card image cap">
                              <div class="card-body">
                                   <h4>{{ post.title }}</h4>
                                  <p class="card-text">{{ post.content }}</p>
                                  {% if post.modify_date %}
                                  <p class="card-text">
                                      {{ post.modify_date }} (수정)

                                      {% if request.user == post.author %}
                                      <a href="{% url 'facebook:post_modify' post.id  %}"
                                         class="btn btn-sm btn-outline-secondary">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                      </a>
                                      <a href="{% url 'facebook:post_delete' post.id  %}" class="btn btn-sm btn-outline-secondary delete">
                                           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                              <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                            </svg>
                                      </a>
                                      {% endif %}
                                  </p>
                                  {% else %}
                                  <p class="card-text">
                                      {{ post.create_date }}

                                      {% if request.user == post.author %}
                                      <a href="{% url 'facebook:post_modify' post.id  %}"
                                         class="btn btn-sm btn-outline-secondary">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                      </a>
                                      <a href="{% url 'facebook:post_delete' post.id  %}" class="btn btn-sm btn-outline-secondary delete">
                                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                              <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                            </svg>
                                      </a>
                                      {% endif %}
                                  </p>
                                  {% endif %}



                                  <p class="card-text">
                                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                          <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                        </svg>
                                      {{ post.voter.count }}
                                  </p>


                                  <center>
                                      <a class="btn btn-primary btn-lg" href="{% url 'facebook:vote_post' post.id 'home' %}" class="recommend btn btn-sm btn-secondary btn-block my-1" style="width:45%;">
                                          <h5>
                                              {% confirm_like request.user.username post.id as l %}
                                              {% if l == 'like' %}
                                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                                </svg>
                                              {% else %}
                                                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                                   <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                               </svg>
                                              {% endif %}
                                              좋아요
                                          </h5>
                                      </a>
                                      <a class="btn btn-primary btn-lg" href="{% url 'facebook:comment_create_post' post.id 'home' %}" class="recommend btn btn-sm btn-secondary btn-block my-1" style="width:45%;">
                                          <h5>
                                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left" viewBox="0 0 16 16">
                                                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                                </svg>
                                              댓글 달기
                                          </h5>
                                      </a>
                                  </center>



                                  {% if post.comment_set.count > 0 %}
                                    <div class="mt-3">
                                    {% for comment in post.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                                        <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                                            <span>
                                                - {{ comment.author }},
                                                {% if comment.modify_date %}
                                                {{ comment.modify_date }} (수정)
                                                {% else %}
                                                {{ comment.create_date }}
                                                {% endif %}
                                            </span>
                                            {% if request.user == comment.author %}
                                            <a href="{% url 'facebook:comment_modify_post' comment.id 'post' %}" class="small">수정</a>,
                                            <a href="{% url 'facebook:comment_delete_post' comment.id 'post' %}" class="small delete">삭제</a>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                    </div>
                                    {% endif %}


                              </div>
                          </div>
                      </div>
                  </div>
                  <br>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
</div>

{% endblock %}